### ISSUE TITLE
Help command gives internal error

### ISSUE THREAD

**Issue by Shadowgar** [DSH105/HoloAPI#36] opened 2014-03-26 10:00 UTC
Using Build #155 with mcpc-plus-1.6.4-R2.1-forge965-B250 typing /holo help created an internal error. 

```
2014-03-26 03:58:16 [INFO] ShadowGar issued server command: /holo help
2014-03-26 03:58:16 [WARNING] [Reflection] Failed to find matching class for: net.minecraft.server.NBTTagCompound
2014-03-26 03:58:16 [INFO] [HoloAPI] [0;31;1m[WARNING] Failed to find a matching method with name: save[m
2014-03-26 03:58:16 [SEVERE] java.lang.NoSuchMethodException: net.minecraft.item.ItemStack.save(null)
2014-03-26 03:58:16 [SEVERE]    at java.lang.Class.getDeclaredMethod(Class.java:2004)
2014-03-26 03:58:16 [SEVERE]    at com.dsh105.holoapi.reflection.SafeMethod.<init>(SafeMethod.java:42)
2014-03-26 03:58:16 [SEVERE]    at com.dsh105.holoapi.util.fanciful.FancyMessage.itemTooltip(FancyMessage.java:146)
2014-03-26 03:58:16 [SEVERE]    at com.dsh105.holoapi.command.HelpEntry.getFancyMessage(HelpEntry.java:78)
2014-03-26 03:58:16 [SEVERE]    at com.dsh105.holoapi.command.HoloCommand.getHelp(HoloCommand.java:75)
2014-03-26 03:58:16 [SEVERE]    at com.dsh105.holoapi.command.HoloCommand.onCommand(HoloCommand.java:85)
2014-03-26 03:58:16 [SEVERE]    at com.dsh105.holoapi.command.DynamicPluginCommand.execute(DynamicPluginCommand.java:44)
2014-03-26 03:58:16 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
2014-03-26 03:58:16 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:533)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1405)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1269)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1201)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:68)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
2014-03-26 03:58:16 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2014-03-26 03:58:16 [WARNING] [Reflection] Failed to find matching class for: net.minecraft.server.NBTTagCompound
2014-03-26 03:58:16 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing 'holo help' in com.dsh105.holoapi.command.DynamicPluginCommand(holo)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:533)
    at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1405)
    at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1269)
    at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1201)
    at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:68)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NullPointerException
    at com.dsh105.holoapi.reflection.SafeConstructor.<init>(SafeConstructor.java:37)
    at com.dsh105.holoapi.util.fanciful.FancyMessage.itemTooltip(FancyMessage.java:146)
    at com.dsh105.holoapi.command.HelpEntry.getFancyMessage(HelpEntry.java:78)
    at com.dsh105.holoapi.command.HoloCommand.getHelp(HoloCommand.java:75)
    at com.dsh105.holoapi.command.HoloCommand.onCommand(HoloCommand.java:85)
    at com.dsh105.holoapi.command.DynamicPluginCommand.execute(DynamicPluginCommand.java:44)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
```

**Comment by Shadowgar** [comment] 2014-03-26 10:08
Also noticed that when creating a holo, when I type "done" nothing happens. No errors nor any messages. When I type /holo info it tells me I have no active displays.

**Comment by Shadowgar** [comment] 2014-03-26 23:22
Just to keep this updated. Builds #161 and above now work with help commands. 
Trying to create hologram text and images produce this result.

```
2014-03-26 04:49:31 [WARNING] [Reflection] Failed to find matching class for: net.minecraft.server.v1_6_R3.Packet
2014-03-26 04:49:31 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing 'holo create image myfavouriteimage' in com.dsh105.holoapi.command.DynamicPluginCommand(holo)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196)
        at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:533)
        at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1405)
        at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1269)
        at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1201)
        at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:68)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
        at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
        at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
        at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NullPointerException
        at com.dsh105.holoapi.reflection.SafeField.<init>(SafeField.java:37)
        at com.dsh105.holoapi.util.wrapper.protocol.Packet.<init>(Packet.java:55)
        at com.dsh105.holoapi.util.wrapper.protocol.Packet.<init>(Packet.java:39)
        at com.dsh105.holoapi.util.wrapper.WrapperPacketAttachEntity.<init>(WrapperPacketAttachEntity.java:26)
        at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:495)
        at com.dsh105.holoapi.api.Hologram.show(Hologram.java:411)
        at com.dsh105.holoapi.api.Hologram.show(Hologram.java:385)
        at com.dsh105.holoapi.api.HologramFactory.build(HologramFactory.java:233)
        at com.dsh105.holoapi.command.HoloCommand.onCommand(HoloCommand.java:150)
        at com.dsh105.holoapi.command.DynamicPluginCommand.execute(DynamicPluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
```

**Comment by DSH105** [comment] 2014-04-22 00:10
HoloAPI should now support MCPC+ servers. There will be an error on MCPC+ 1.7 whenever a player logs in, but that just means that Touchscreen holograms won't work. We are working to fix this.

**Comment by DSH105** [comment] 2014-04-22 07:51
Closing this as MCPC+ support has been added (with the exception of the issue I mentioned above). Reopen or create a new issue if it's not working as intended ;).

**Closed as completed by DSH105** 2014-04-22 07:51 UTC
