### ISSUE TITLE
Can't Create Holograms - Modded Server

### ISSUE THREAD

**Issue by TalonPhoenix** [DSH105/HoloAPI#35] opened 2014-03-26 04:17 UTC
When attempting to create a hologram, I enter the lines and type done. It registers the lines, but when I type "done", nothing happens. No error message, no hologram. In the newest version (v1.1.1), I also cannot access "/holo help", there was an internal server error. I tried an older version, however, and was able to use "/holo help" but still had the same error when attempting to create a hologram.

I'm running a 1.6.4 modded pixelmon server. I couldn't find any information about whether this mod is compatible. I'm not sure what other information I need to provide in order to receive assistance.

Also, I have not made any changes to the config or any other files.

**Comment by DSH105** [comment] 2014-03-26 05:14
Modded servers are not currently supported. We are working on this :).

The issue with the help menu was fixed here: https://github.com/DSH105/HoloAPI/commit/188f581b5e6d5ba1b41c5a2e613db49c9dcb1384

**Comment by DSH105** [comment] 2014-04-03 05:50
Closing this as a duplicate of #36 as it has more information and commit history on this issue. We will try to add support for modded servers as soon as possible :).

**Closed as completed** 2014-04-03 05:50 UTC
