### ISSUE TITLE
Damage indicators stuck

### ISSUE THREAD

**Issue by Adondriel** [DSH105/HoloAPI#19] opened 2014-03-12 16:18 UTC
I am having issues with damage indicators.
Sometimes the damage indicator tags get stuck in the air, not being delete until i restart the server.
I am using dev build #90

**Comment by BriannaThorez** [comment] 2014-03-12 19:50
same. But mine clear on /holoreload and relog onto server

**Comment by DSH105** [comment] 2014-03-12 19:51
We are looking into the issue :)

**Comment by Adondriel** [comment] 2014-03-13 11:55
I am using a multi world plug in if that is of any help.

**Comment by DSH105** [comment] 2014-03-14 10:05
Closing as a duplicate of #18

**Closed as completed by DSH105** 2014-03-14 10:05 UTC
Labels: bug, duplicate
